apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dev-mongo-worker-1
  labels:
    app: mongo-worker
    env: dev
spec:
  capacity:
    storage: 17Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/data/mongodb
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1